# Generated by Django 2.2 on 2019-04-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='Cantidad_producto',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productos',
            name='Precio_producto',
            field=models.FloatField(),
        ),
    ]
