# Generated by Django 2.2 on 2019-04-04 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_compras', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Envio', models.IntegerField(blank=True)),
                ('Total', models.FloatField(blank=True)),
                ('Nombre_tarjeta', models.CharField(max_length=100)),
                ('Mes_tarjeta', models.IntegerField(blank=True)),
                ('año_tarjeta', models.IntegerField(blank=True)),
                ('CodigoSeg_Tarjeta', models.IntegerField(blank=True)),
                ('Numero_tarjeta', models.IntegerField(blank=True)),
                ('Productos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.Productos')),
            ],
        ),
        migrations.CreateModel(
            name='ComprasProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Compras', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Compras.Compras')),
                ('Productos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.Productos')),
            ],
        ),
        migrations.AddField(
            model_name='compras',
            name='Pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Compras.Pago'),
        ),
        migrations.AddField(
            model_name='compras',
            name='Usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
