# Generated by Django 2.2 on 2019-04-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='Fecha_compras',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pago',
            name='CodigoSeg_Tarjeta',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='pago',
            name='Envio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pago',
            name='Mes_tarjeta',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='pago',
            name='Numero_tarjeta',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='pago',
            name='Total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pago',
            name='año_tarjeta',
            field=models.CharField(max_length=2),
        ),
    ]
