# Generated by Django 2.2 on 2019-04-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0002_auto_20190405_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='Fecha_compras',
            field=models.DateField(auto_now_add=True),
        ),
    ]
